CREATE TABLE cars
(
    id BIGINT NOT NULL AUTO_INCREMENT,
    model VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    inventory INT NOT NULL,
    daily_fee DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (id)
);
